name: Build & Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # for checkout
      packages: write      # for pushing to GHCR
      id-token: write      # if using OIDC for kubectl login
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/FlytIT/utility/update-ghcr-secret:latest

      - name: Image digest
        run: echo ::set-output name=digest::$(docker buildx imagetools inspect ghcr.io/FlytIT/utility/update-ghcr-secret:latest --format '{{.Digest}}')
